{
 "title": "EnviroDashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Air quality",
   "type": "timeseries",
   "description": "Oxidising: gas resistance for oxidising gases.\nEg chlorine, nitrous oxide\n\nReducing:  gas resistance for reducing gases.\nEg hydrogen, carbon monoxide\n\nNH3: gas resistance for nh3/ammonia\n   ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "database": "\"enviroDB\"",
     "measure": "sensor_data",
     "rawQuery": "select time, cast(oxidising as double) as oxidising\r\nfrom \"enviroDB\".\"enviroTable\"\r\nORDER BY time ASC",
     "table": "\"enviroTable\""
    },
    {
     "database": "\"enviroDB\"",
     "measure": "sensor_data",
     "rawQuery": "select time, cast(reducing as double) as reducing\r\nfrom \"enviroDB\".\"enviroTable\"\r\nORDER BY time ASC",
     "table": "\"enviroTable\""
    },
    {
     "database": "\"enviroDB\"",
     "measure": "sensor_data",
     "rawQuery": "select time, cast(nh3 as double) as nh3\r\nfrom \"enviroDB\".\"enviroTable\"\r\nORDER BY time ASC",
     "table": "\"enviroTable\""
    }
   ]
  },
  {
   "title": "Brightness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "database": "\"enviroDB\"",
     "measure": "sensor_data",
     "rawQuery": "select time, cast(brightness as double) as brightness\r\nfrom \"enviroDB\".\"enviroTable\"\r\nORDER BY time ASC\r\n",
     "table": "\"enviroTable\""
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "\"enviroDB\"",
     "measure": "sensor_data",
     "rawQuery": "select time, cast(humidity as double) as humidity\r\nfrom \"enviroDB\".\"enviroTable\"\r\nORDER BY time ASC",
     "table": "\"enviroTable\""
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"enviroDB\"",
     "measure": "sensor_data",
     "rawQuery": "select time, cast(temperature as double) as temperature\r\nfrom \"enviroDB\".\"enviroTable\"\r\nORDER BY time ASC",
     "table": "\"enviroTable\""
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "database": "\"enviroDB\"",
     "measure": "sensor_data",
     "rawQuery": "select time, cast(pressure as double) as pressure\r\nfrom \"enviroDB\".\"enviroTable\"\r\nORDER BY time ASC",
     "table": "\"enviroTable\""
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "database": "\"enviroDB\"",
     "measure": "sensor_data",
     "rawQuery": "select * from \"enviroDB\".\"enviroTable\" ",
     "table": "\"enviroTable\""
    }
   ]
  }
 ]
}